//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Snooker.rc
//
#define IDD_ABOUT_DIALOG                100
#define IDR_MAINFRAME                   128
#define IDS_NOT_SUPPORTED               129
#define IDD_DISPLAY_DIALOG              130
#define IDS_CLASS_NAME                  130
#define IDS_ERROR_CREATE_WINDOW         131
#define IDD_TRIANGLES_DIALOG            131
#define IDS_ERROR_SET_DISPLAY_MODE      132
#define IDD_MENU_DIALOG                 132
#define IDS_WINDOW_TITLE                133
#define IDD_NEW_GAME_DIALOG             133
#define IDS_ERROR_REGISTER_CLASS        134
#define IDD_BALLS_DIALOG                134
#define IDS_DEFAULTEXT                  135
#define IDD_HELP_DIALOG                 135
#define IDS_FILTER                      136
#define IDC_RESOLUTIONS                 1000
#define IDC_FULLSCREEN                  1001
#define IDC_DONT_ASK_AGAIN              1002
#define IDC_TRIANGLE_BX                 1007
#define IDC_TRIANGLE_CX                 1008
#define IDC_TRIANGLE_AX                 1009
#define IDC_TRIANGLE_AY                 1010
#define IDC_TRIANGLE_BY                 1011
#define IDC_TRIANGLE_CY                 1012
#define IDC_TRIANGLE_AZ                 1013
#define IDC_TRIANGLE_BZ                 1014
#define IDC_TRIANGLE_CZ                 1015
#define IDC_TRIANGLE_NX                 1016
#define IDC_TRIANGLE_NY                 1017
#define IDC_TRIANGLE_NZ                 1018
#define IDC_BALL_POSITIONX              1019
#define IDC_TRIANGLE_AX_SPIN            1020
#define IDC_TRIANGLE_BX_SPIN            1021
#define IDC_TRIANGLE_CX_SPIN            1022
#define IDC_TRIANGLE_AY_SPIN            1023
#define IDC_TRIANGLE_BY_SPIN            1024
#define IDC_TRIANGLE_CY_SPIN            1025
#define IDC_TRIANGLE_AZ_SPIN            1026
#define IDC_TRIANGLE_BZ_SPIN            1027
#define IDC_TRIANGLE_CZ_SPIN            1028
#define IDC_TRIANGLE_HOLE               1031
#define IDC_BALL_COLOR0_SPIN            1032
#define IDC_TRIANGLE_ADD                1033
#define IDC_TRIANGLE_DELETE             1034
#define IDC_TRIANGLE_PREVIOUS           1035
#define IDC_TRIANGLE_NEXT               1036
#define IDC_BALL_DELETE                 1037
#define IDC_BALL_ADD                    1038
#define IDC_BALL_PREVIOUS               1039
#define IDC_BALL_NEXT                   1040
#define IDC_BALL_SCORE                  1041
#define IDC_BALL_RAY                    1042
#define IDC_BALL_MASS                   1043
#define IDC_BALL_COLOR0                 1044
#define IDC_BALL_COLOR1                 1045
#define IDC_BALL_COLOR2                 1046
#define IDC_BALL_COLOR3                 1047
#define IDC_BALL_POSITIONY              1048
#define IDC_BALL_POSITIONZ              1049
#define IDC_BALL_POSITIONX_SPIN         1050
#define IDC_BALL_COLOR1_SPIN            1051
#define IDC_BALL_COLOR2_SPIN            1052
#define IDC_BALL_COLOR3_SPIN            1053
#define IDC_BALL_POSITIONY_SPIN         1054
#define IDC_BALL_POSITIONZ_SPIN         1055
#define IDC_BALL_SCORE_SPIN             1056
#define IDC_BALL_RAY_SPIN               1057
#define IDC_BALL_MASS_SPIN              1058
#define IDC_TRIANGLE_STATIC             1060
#define IDC_BALL_WHITE                  1061
#define IDC_TRIANGLE_REFLECT            1061
#define IDC_NEW_GAME                    1062
#define IDC_TRENNING                    1063
#define IDC_LOAD_GAME                   1064
#define IDC_SAVE_GAME                   1065
#define IDC_ABOUT                       1066
#define IDC_EXIT                        1067
#define IDC_PLAYER1                     1068
#define IDC_PLAYER2                     1069
#define IDC_BALLS                       1072
#define IDC_TRIANGLES                   1073
#define IDC_RENDER_TABLE                1074
#define IDC_RENDER_TRIANGLES            1075
#define IDC_RENDER_TRIANGLE             1076
#define IDC_TRIANGLE_NAME               1077
#define IDC_TRIANGLE_N_SPIN             1079
#define IDC_BALL_RED                    1080
#define IDC_BALL_COLOR                  1082
#define IDC_HELPBTN                     1083
#define IDC_BUTTON1                     1084
#define IDC_RETURN                      1085
#define ID_MENU_DIALOG                  32773
#define ID_LOAD_CAMERA1                 32774
#define ID_LOAD_CAMERA2                 32775
#define ID_LOAD_CAMERA3                 32776
#define ID_LOAD_CAMERA4                 32777
#define ID_LOAD_CAMERA5                 32778
#define ID_LOAD_CAMERA6                 32779
#define ID_LOAD_CAMERA7                 32780
#define ID_LOAD_CAMERA8                 32781
#define ID_STORE_CAMERA1                32782
#define ID_STORE_CAMERA2                32783
#define ID_STORE_CAMERA3                32784
#define ID_STORE_CAMERA4                32785
#define ID_STORE_CAMERA5                32786
#define ID_STORE_CAMERA6                32787
#define ID_STORE_CAMERA7                32788
#define ID_STORE_CAMERA8                32789
#define ID_BALLS_DIALOG                 32790
#define ID_TRIANGLES_DIALOG             32791
#define ID_SAVE_DEFAULT                 32792
#define ID_ABOUT_DIALOG                 32794
#define ID_NEW_GAME_DIALOG              32796

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        136
#define _APS_NEXT_COMMAND_VALUE         32798
#define _APS_NEXT_CONTROL_VALUE         1086
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
